#ftp
ftp_server: 15.83.240.98
ftp_username: sh\automation
ftp_password: Shanghai2014
RDP_Server:
  rfx_win7: rfxwin7-auto
  rfx_win10: rfxw10-auto
  win7_on_esx: Linux-w764-c01
  win10_on_HyperV: rfxw10-auto
  win10_on_HyperV1: rfxw10-auto
  win10_on_esx: Linux-w10-c01
  Freerdp_rd_gateway_w2012: W2012TSG.test.com
  win10: rfxw10-auto
  rfxw81-auto: rfxw81-auto  #test for special user account
Offset_Map:
  rdp_icon: [Test_Data/RDP/rdp_icon_10_5.png, Test_Data/RDP/rdp_icon1_10_5.png, Test_Data/RDP/rdp_icon2_10_5.png]
  rdp_icon_active: [Test_Data/RDP/rdp_icon_active_10_5.png]
  rdp_certificate_accept: [Test_Data/RDP/rdp_certificate_accept_5_5.png, Test_Data/RDP/rdp_certificate_accept1_5_5.png]
  top_left: [Test_Data/RDP/rdp_title_0_0.png, Test_Data/RDP/rdp_title1_0_0.png]
  error_wnd: [Test_Data/RDP/rdp_server_error_5_5.png]
  close_button: [Test_Data/RDP/rdp_close_5_5.png]
  network: [40,70]
  service: [40,100]
  window: [40,130]
  options: [40,160]
  local_resources: [40,180]
  experience: [40, 220]
  diagnostics: [40, 250]
  advanced: [40, 280]
  connection_name: [500,80]
  address: [500,110]
  single_sign_on: [200,180]
  ask_for_credentials: [200,210]
  user_password: [200,240]
  username_box: [500,280]
  password_box: [500,310]
  domain_box: [500,340]
  ok_button: [Test_Data/RDP/rdp_ok_5_3.png]
  apply_button: [420,580]
  cancel_button: [580,580]
  key_usbr: [420,195]
  key_mapping: [320,195]
RDP_Logon_Win10:
  Server: rfx_win10
  Username: automation
  Password: Shanghai2014
  Domain: sh.dto
RDP_Logon_SpecUser1:
  Server: rfxw81_auto
  Username: spcpass11
  Password: '!@#$%^&*()'
  Domain: sh.dto
RDP_Logon_SpecUser2:
  Server: rfxw81-auto
  Username: spcpass21
  Password: +=_,-?<>~
  Domain: sh.dto
RDP_Logon_SpecUser3:
  Server: rfxw81-auto
  Username: spcpass31
  Password: /;[]{}:|
  Domain: sh.dto
RDP_Logon_SpecUser4:
  Server: rfxw81-auto
  Username: space user1
  Password: ' space user'
  Domain: sh.dto
RDP_Logon_SpecUser5:
  Server: rfxw81-auto
  Username: '!~#$%^&()_-`{}'''
  Password: neoware
  Domain: sh.dto
RDP_Logon_SpecUser6:
  Server: rfxw81-auto
  Username: spcpass71
  Password: S\123456789
  Domain: sh.dto

#wireless
R1_TC_2.4G_n_WPA2P: WPA2P
WPA2P_password: neoware1234

#static
R1_TC_5G_n: static
static_wireless_password: ''

#hidden_wireless
R1_Linux_TKIP: R1-Linux-TKIP
hidden_wireless_password: ~!@#$%^&*()_+{}|:"<>? -=[]\;',./

wireless_pictures:
  1920x1200:
    add: [add]
    apply: [apply]
    delete: [delete]
    edit: [edit]
    IPv4: [IPv4]
    network_icon: [network_icon]
    ok_button: [ok_button]
    R1-Linux-TKIP_connect: [R1-Linux-TKIP_connect]
    scan_ap: [scan_ap]
    scanning: [scanning]
    security: [security]
    static: [static]
    static_connect: [static_connect]
    WPA2P: [WPA2P]
    WPA2P_connect: [WPA2P_connect]
    WPA2P_security: [WPA2P_security]
  1366x768:
    add: [add]
    apply: [apply]
    delete: [delete]
    edit: [edit]
    IPv4: [IPv4]
    network_icon: [network_icon]
    ok_button: [ok_button]
    R1-Linux-TKIP_connect: [R1-Linux-TKIP_connect]
    scan_ap: [scan_ap]
    scanning: [scanning]
    security: [security]
    static: [static]
    static_connect: [static_connect]
    WPA2P: [WPA2P]
    WPA2P_connect: [WPA2P_connect]
    WPA2P_security: [WPA2P_security]

#view_config
blast_server_name: blast_win10
pcoip_server_name: pcoip_win10
rdp_server_name: rdp_win10
view_server: vnsvr.sh.dto
spec_server_name_1: vmware_spec_1
spec_server_name_2: vmware_spec_2
spec_server_name_3: vmware_spec_3
spec_server_name_4: vmware_spec_4
spec_server_name_5: vmware_spec_5
spec_server_name_6: vmware_spec_6
view_pictures:
  1920x1200:
    blast_win10: [blast_win10, blast_win10_1]
    connect_desktop_fail: [connect_desktop_fail]
    connect_fail: [connect_fail, connect_fail_1]
    ok: [ok]
    pcoip_win10: [pcoip_win10, pcoip_win10_1]
    rdp_win10: [rdp_win10, rdp_win10_1]
    refuse: [refuse, refuse_1, refuse_2]
    Security: [Security]
    view_edit: [view_edit, view_edit_1]
    view_icon: [view_icon, view_icon_1]
    view_usbr: [view_usbr]
    vm_window: [vm_window, vm_window_1]
    vmware_spec: [vmware_spec]
    vmware_in_task_bar: [vmware_in_task_bar]
  1366x768:
    blast_win10: [blast_win10, blast_win10_1]
    connect_desktop_fail: [connect_desktop_fail]
    connect_fail: [connect_fail, connect_fail_1]
    ok: [ok]
    pcoip_win10: [pcoip_win10, pcoip_win10_1]
    rdp_win10: [rdp_win10, rdp_win10_1]
    refuse: [refuse, refuse_1]
    Security: [Security]
    view_edit: [view_edit]
    view_icon: [view_icon]
    view_usbr: [view_usbr]
    vm_window: [vm_window]
    vmware_spec: [vmware_spec]
    vmware_in_task_bar: [vmware_in_task_bar]

#Credentials
username: automation
password: Shanghai2014
domain: sh

spec_username1: spcpass11
spec_password1: '!@#$%^&*()'
spec_username2: spcpass21
spec_password2: '+=_,-?<>~'
spec_username3: spcpass31
spec_password3: '/;[]{}:|'
spec_username4: 'space user1'
spec_password4: ' space user'
spec_username5: '!~#$%^&()_-`{}'''
spec_password5: neoware
spec_username6: spcpass71
spec_password6: 'S\123456789'

#certificate
cert_pictures:
  1920x1200:
    control_panel: [control_panel, control_panel_1]
    import_success: [import_success]
    import_url: [import_url]
    remove: [remove]
    ROOTCA: [ROOTCA]
  1366x768:
    control_panel: [control_panel]
    import_success: [import_success]
    import_url: [import_url]
    remove: [remove]
    ROOTCA: [ROOTCA]

#ssh
ssh_server_address: 15.83.240.64
ssh_user_name: neoware
ssh_pass_word: neoware
#telnet
telnet_server_address: 15.83.240.64
telnet_user_name: neoware
telnet_pass_word: neoware
