#Check_System_information.run(): Y
#Connect_Cisco_VPN.run(): Y
#Connect_to_SSH_Server.run(): Y
#Connect_to_Telnet_Server.run(): Y
#Connectivity_hidden_wireless.run(): Y
#Connectivity_static_wireless.run(): Y
#Connectivity_WPA2P.run(): Y
#Dynamic_IP_Mode.run(): Y
#FreeRDP_rdp_win10.run(): Y
#FreeRDP_rfx_win10.run(): Y
#FreeRDP_USB_Key_mapping.run(): Y
#FreeRDP_USB_Key_USBR.run(): Y
#FreeRDP_USB_Printer_mapping.run(): Y
#FreeRDP_win10_smartcard.run(): Y
FreeRDP_win10_with_spec.run(): Y
#Local_USB_printer_print_test_page.run(): Y
Static_IP_mode_works.run(): Y
Verify_can_add_certificate.run(): Y
VMware_Connect_with_Certificate.run(): Y
VMware_win10_blast.run(): Y
VMware_win10_pcoip.run(): Y
VMware_win10_rdp.run(): Y
VMware_win10_USB_key_USBR_blast.run(): Y
VMware_win10_USB_key_USBR_pcoip.run(): Y
VMware_win10_with_Spec.run(): Y
XenDesktop_PNagent_USB_key_mapping.run(): Y
XenDesktop_PNagent_USB_key_USBR.run(): Y
XenDesktop_Storefront_connect_to_win10.run(): Y
#XenDesktop_Storefront_USB_printer_mapping.run(): Y
#XenDesktop_Storefront_win10_smartcard.run(): Y
XenDesktop_Storefront_win10_USB_key_mapping.run(): Y
XenDesktop_Storefront_win10_USB_key_USBR.run(): Y

