USB_Update:
- 237.5
- 471.0
add_printer:
- 31.0
- 156.5
chose_printer:
- 115.0
- 108.0
confirm:
- 1017.0
- 507.5
confirm_deletion:
- 384.0
- 90.0
delete_printer:
- 92.5
- 135.0
prepare_print:
- 1020.5
- 509.0
print_test_page:
- 261.0
- 96.0
printer_properties:
- 601.0
- 352.0
submit:
- 147.5
- 92.0
apply_network_change:
- 828.0
- 613.5
apply_vnc_change:
- 828.0
- 575.5
enable_vnc_shadow:
- 281.0
- 64.5
method_of_connection:
- 173.0
- 17.0
apply_vpn_change:
- 820.5
- 610.5
enable_auto_start:
- 536.0
- 87.0
switch_to_vpn:
- 455.0
- 56.0
